name: betfund
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.7
  - pandas=1.0.2
  - flask=1.1.1
  - flask-wtf=0.14.3
  - gunicorn=20.0.4
  - flask-sqlalchemy=2.4.0
  - flask-debugtoolbar=0.10.1
  - pytest
  - pytest-cov
  - jupyterlab
  - psycopg2=2.8.4
  - sqlalchemy=1.3.15
  - flask-login=0.4.1
  - flask-mail=0.9.1
  - pip
  - pip:
    - names
    - werkzeug==0.16.1
    - flask-migrate==2.5.3