"""timestamp to track fund creation

Revision ID: 58076f06e75a
Revises: fd83433ae308
Create Date: 2020-04-10 12:35:23.886809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58076f06e75a'
down_revision = 'fd83433ae308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funds', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
